[package]
name = "thok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.0"
tui = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
rand = "0.8.5"
